version: 0.2
env:
  variables:
    REGION: "us-west-2"
    STAGE: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - serverless -v
      - cd sls-codebuild/sls-f    # <-- this would be relevant to your code structure
      - npm install
  build:
    commands:
      - npm run jest
      - if [[ $? == 1 ]]; then exit; fi
      - echo "SUCCESSFULLY PASSED TESTS!"
      - sls deploy --stage ${STAGE} --region ${REGION} -v
  post_build:
    commands:
      - echo "POST_BUILD STEP"