org: serverlessguru
app: component-app
component: aws-app-sync@dev   # <-- @dev for beta changes, aws-app-sync for stable
name: sls-appsync-example-api

inputs:
  name: ${name}-${stage}
  src: ./src
  authenticationType: 'API_KEY'
  apiKeys:
    - '1234'
  dataSources:
    - type: AWS_LAMBDA
      name: exampleLambda
      config:
        lambdaFunctionArn: ${output:${app}:${stage}:sls-appsync-example-lambda.arn}
  mappingTemplates:
    - dataSource: exampleLambda
      type: Query
      field: getUsers
      request: ./src/vtl/request.vtl
      response: ./src/vtl/response.vtl