version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - npm install newman -g
      - serverless -v
      - newman -v
  build:
    commands:
      - sls deploy -v
  post_build:
    commands:
      - sls offline
      - newman run test.postman_collection.json
      - newman run https://www.getpostman.com/collections/093607256e1a6b4c0deb
