version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - npm install newman -g
      - cd newman-codebuild
      - npm install
  build:
    commands:
      - serverless -v
      - newman -v
  post_build:
    commands:
      - sls offline start --exec "newman run test.postman_collection.json"
      - if [ $? == 1 ]; then exit; fi
      - echo "SUCCESSFULLY PASSED TESTS!"
      - sls deploy

      # failing script:
      # - sls offline start --exec "newman run https://www.getpostman.com/collections/093607256e1a6b4c0deb"
      # - if [ $? == 1 ]; then exit; fi

      # multi-script example. This does NOT work for our use case because only the final script's result is evaluated in following "$?" statement
      # - sls offline start --exec "newman run https://www.getpostman.com/collections/093607256e1a6b4c0deb & newman run test.postman_collection.json"