version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - npm install newman -g
      - cd newman-codebuild
      - npm install
  build:
    commands:
      - serverless -v
      - newman -v
  post_build:
    commands:
      - sls offline start --exec "newman run test.postman_collection.json"
      - if [ $? == 1 ]; then exit; fi
      - sls offline start --exec "newman run https://www.getpostman.com/collections/093607256e1a6b4c0deb"
      - if [ $? == 1 ]; then exit; fi
      # - sls offline start --exec "newman run https://www.getpostman.com/collections/093607256e1a6b4c0deb & newman run test.postman_collection.json"
      - echo "SUCCESSFULLY PASSED SERVER!"
      - sls deploy -v
