version: 0.2
env:
  variables:
    REGION: "us-west-2"
    STAGE: "dev"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install serverless -g
      - serverless -v
      - cd sls-codebuild/sls-f-components
      - (cd src && npm install && npm run jest)
  build:
    commands:
      - cd src && npm install && npm run jest && if [[ $? == 1 ]]; then exit; fi && cd ..
      - echo "SUCCESSFULLY PASSED TESTS!"
      - sls deploy --stage ${STAGE} -v
  post_build:
    commands:
      - echo "POST_BUILD STEP"