EksKubernetesServiceRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: EksKubernetesServiceRole
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - eks.amazonaws.com
          Action: sts:AssumeRole
    ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AmazonEKSClusterPolicy'
      - 'arn:aws:iam::aws:policy/AmazonEKSServicePolicy'
# EKS Nodes
NodeInstanceRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - ec2.amazonaws.com
          Action: sts:AssumeRole
    Path: "/"
    Policies:
      - 
        PolicyName: node
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:Describe*
                - ecr:GetAuthorizationToken
                - ecr:BatchCheckLayerAvailability
                - ecr:GetDownloadUrlForLayer
                - ecr:GetRepositoryPolicy
                - ecr:DescribeRepositories
                - ecr:ListImages
                - ecr:BatchGetImage
              Resource: "*"
      - 
        PolicyName: cni
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Effect: Allow
              Action:
                - ec2:DescribeNetworkInterfaces
                - ec2:DescribeInstances
                - ec2:CreateNetworkInterface
                - ec2:AttachNetworkInterface
                - ec2:DeleteNetworkInterface
                - ec2:DetachNetworkInterface
                - ec2:ModifyNetworkInterfaceAttribute
                - ec2:AssignPrivateIpAddresses
                - tag:TagResources
              Resource: "*"
      - 
        PolicyName: eks
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Effect: Allow
              Action:
                - eks:DescribeCluster
              Resource: "*"
      - 
        PolicyName: s3-management
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
                - s3:DeleteObject
              Resource:
                - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevuploads, Arn ]
                - Fn::Join:
                    - "/"
                    -
                      - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevuploads, Arn ]
                      - "*"
            - 
              Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:ListBucket
                - s3:DeleteObject
              Resource:
                - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevthumbnails, Arn ]
                - Fn::Join:
                    - "/"
                    -
                      - Fn::GetAtt: [ S3BucketAwseksspotserverlessdemodevthumbnails, Arn ]
                      - "*"
            - 
              Effect: Allow
              Action:
                - s3:HeadBucket
              Resource: '*'
      - 
        PolicyName: ClusterAutoscaler
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Action:
                - ec2:DescribeRegions
                - ec2:DescribeInstances
              Resource: "*"
            -
              Effect: Allow
              Action:
                - ecr:GetAuthorizationToken
                - ecr:BatchCheckLayerAvailability
                - ecr:GetDownloadUrlForLayer
                - ecr:GetRepositoryPolicy
                - ecr:DescribeRepositories
                - ecr:ListImages
                - ecr:BatchGetImage
              Resource: "*"
            -
              Effect: Allow
              Action:
                - autoscaling:DescribeAutoScalingGroups
                - autoscaling:DescribeAutoScalingInstances
                - autoscaling:DescribeLaunchConfigurations
                - autoscaling:SetDesiredCapacity
                - autoscaling:DescribeTags
                - autoscaling:TerminateInstanceInAutoScalingGroup
              Resource: "*"
NodeInstanceProfile:
  Type: AWS::IAM::InstanceProfile
  Properties:
    Path: "/"
    Roles:
      - Ref: NodeInstanceRole