org: serverlessguru
app: serverless-app

service: serverless-app-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-west-2"}
  profile: ${opt:profile, "default"}

plugins:
  - serverless-offline

package:
  exclude:
    - ./**
  include:
    - index.js

custom:
  base: ${self:service}-${self:provider.stage}

functions:
  test:
    name: ${self:custom.base}-test
    handler: index.handler
    description: test function for initial API deployment
    events:
      - http:
          path: /test
          method: any
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - version
              - x-uuid
outputs:
  ApiEndpoint:
    Fn::Join:
      - ''
      - - https://
        - Ref: ApiGatewayRestApi
        - .execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}
  ApiId:
    Ref: ApiGatewayRestApi
  ApiResourceId:
    Fn::GetAtt:
    - ApiGatewayRestApi
    - RootResourceId 