org: serverlessguru
app: components-app
component: aws-lambda
name: monolithApi
stage: dev
inputs:
  name: ${app}-${name}-${stage} # this references the stage property above
  src: ./src
  handler: api.handler