org: serverlessguru  # <-- change to your org
app: sls-fargate-eks  # <-- change to your app name
service: ${self:app}
provider:
  name: aws
  stage: ${opt:stage, "dev"}  # <-- change to your default stage
  region: ${opt:region, "us-east-1"}
custom:
  base: ${self:provider.stage}-${self:provider.region}

  # outputs path
  vpcStackName: sg-networking-infra:${self:provider.stage}:${self:provider.region}:sg-networking-infra-vpc

  # Serverless Framework Pro params/outputs
  outputs:
    VPCId: ${output:${self:custom.vpcStackName}.VPCId}
    VPCSecurityGroup: ${output:${self:custom.vpcStackName}.VPCSecurityGroup}
    SubnetA: ${output:${self:custom.vpcStackName}.SubnetA}
    SubnetB: ${output:${self:custom.vpcStackName}.SubnetB}

resources:
  - ${file(./resources/iam.yml)}
  - ${file(./resources/security-groups.yml)}
  - ${file(./resources/eks.yml)}
